In [3]:
import torch
import numpy as np

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.18702086, 0.50636826, 0.90226063, 0.34586043],
       [0.50573353, 0.86595791, 0.26876337, 0.92839711],
       [0.27237933, 0.24690209, 0.43399089, 0.66420269]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.2406, -0.2080,  1.4463,  0.8297],
        [-0.4742,  0.0252, -0.3327, -0.5637],
        [-1.9765, -1.6530, -0.1386,  0.0894]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1870, 0.5064, 0.9023, 0.3459],
        [0.5057, 0.8660, 0.2688, 0.9284],
        [0.2724, 0.2469, 0.4340, 0.6642]], dtype=torch.float64)

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])